In [49]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

In [50]:
data = sns.load_dataset("titanic")
data.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

### EDA

In [51]:
data.shape

(891, 15)

In [52]:
data.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')

In [53]:
data.describe()

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [54]:
data.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [55]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    str     
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    str     
 8   class        891 non-null    category
 9   who          891 non-null    str     
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str     
 13  alive        891 non-null    str     
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB


In [56]:
# drop deck, embark_town,
data.drop(["deck","embark_town","alive","class","who","adult_male"],axis=1,inplace=True)

In [57]:
data.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0         0       3    male  22.0      1      0   7.2500        S  False
1         1       1  female  38.0      1      0  71.2833        C  False
2         1       3  female  26.0      0      0   7.9250        S   True
3         1       1  female  35.0      1      0  53.1000        S  False
4         0       3    male  35.0      0      0   8.0500        S   True

In [58]:
data.describe()

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [59]:
# fill null ages with mean
data["age"]=data["age"].fillna(data["age"].mean(),inplace=True)

In [60]:
data.describe()

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  891.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   13.002015    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   22.000000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   29.699118    0.000000    0.000000   14.454200
75%      1.000000    3.000000   35.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [61]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    str    
 3   age       891 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   fare      891 non-null    float64
 7   embarked  889 non-null    str    
 8   alone     891 non-null    bool   
dtypes: bool(1), float64(2), int64(4), str(2)
memory usage: 56.7 KB


In [62]:
# instead of filling those 2 rows in embarked, delete those 2 null rows
data.dropna(subset=["embarked"],inplace=True)

In [63]:
data.info()

<class 'pandas.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  889 non-null    int64  
 1   pclass    889 non-null    int64  
 2   sex       889 non-null    str    
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64  
 5   parch     889 non-null    int64  
 6   fare      889 non-null    float64
 7   embarked  889 non-null    str    
 8   alone     889 non-null    bool   
dtypes: bool(1), float64(2), int64(4), str(2)
memory usage: 63.4 KB


In [64]:
# we have to predict survived column
# label encode
from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()

# label encode sex and embarked
data["sex"] = enc.fit_transform(data["sex"])
data["embarked"] = enc.fit_transform(data["embarked"])

In [65]:
data.head()

survived  pclass  sex   age  sibsp  parch     fare  embarked  alone
0         0       3    1  22.0      1      0   7.2500         2  False
1         1       1    0  38.0      1      0  71.2833         0  False
2         1       3    0  26.0      0      0   7.9250         2   True
3         1       1    0  35.0      1      0  53.1000         2  False
4         0       3    1  35.0      0      0   8.0500         2   True

In [66]:
data = data.astype(int)

In [67]:
data.head()

survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0         0       3    1   22      1      0     7         2      0
1         1       1    0   38      1      0    71         0      0
2         1       3    0   26      0      0     7         2      1
3         1       1    0   35      1      0    53         2      0
4         0       3    1   35      0      0     8         2      1

In [68]:
data["pclass"].value_counts()

pclass
3    491
1    214
2    184
Name: count, dtype: int64

In [69]:
# in X we keep input, in Y output
X = data.drop("survived",axis = 1)
Y = data["survived"]


In [70]:
# train test split
from sklearn.model_selection import train_test_split

X_Train, X_Test, y_train, y_test = train_test_split(X,Y,test_size=0.2)


In [71]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X=X_Train,y=y_train)

LogisticRegression()

In [73]:
y_test

732    0
546    1
5      0
622    1
752    0
      ..
676    0
368    1
202    0
208    1
118    0
Name: survived, Length: 178, dtype: int64

In [75]:
y_pred = model.predict(X=X_Test)
print(y_pred)

[0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 1 1 0 0 0 1 0 1 1 0 0 0 0 1 0 1 0
 0 1 0 1 1 1 0 0 0 0 1 0 0 1 0 1 0 0 0 0 1 0 0 0 1 1 0 1 1 1 1 1 0 0 1 0 1
 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 1 0 1 1 0 1 0 0 0 0 0 0 1 0 0
 1 1 0 1 1 0 1 1 1 1 0 1 1 0 1 1 0 1 0 0 0 0 0 1 1 1 1 0 1 0 0 0 0 0 0 1 0
 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 1 0 0 1 0 1 1]


In [76]:
# confusion matrix
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

print("Confusion Matrix: ")
print(confusion_matrix(y_true=y_test, y_pred=y_pred))

print("Accuracy Score: ")
print(accuracy_score(y_true=y_test, y_pred=y_pred))

print("Report: ")
print(classification_report(y_true=y_test, y_pred=y_pred))

Confusion Matrix: 
[[94 12]
 [16 56]]
Accuracy Score: 
0.8426966292134831
Report: 
              precision    recall  f1-score   support

           0       0.85      0.89      0.87       106
           1       0.82      0.78      0.80        72

    accuracy                           0.84       178
   macro avg       0.84      0.83      0.84       178
weighted avg       0.84      0.84      0.84       178



In [77]:
from sklearn.metrics import recall_score, f1_score, accuracy_score, precision_score

accuraccy = accuracy_score(y_true=y_test,y_pred=y_pred)
# print("accuraccy: ", accuraccy)
print("accuraccy: ", accuraccy*100)

precision = precision_score(y_true=y_test,y_pred=y_pred)
# print("precision: ", precision)
print("precision: ", precision*100)

recall = recall_score(y_true=y_test,y_pred=y_pred)
# print("recall: ", recall)
print("recall: ", recall*100)

f1 = f1_score(y_true=y_test, y_pred=y_pred)
# print("F1 scrore: ", f1)
print("F1 scrore: ", f1*100)

accuraccy:  84.26966292134831
precision:  82.35294117647058
recall:  77.77777777777779
F1 scrore:  80.0


In [78]:
data

survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0           0       3    1   22      1      0     7         2      0
1           1       1    0   38      1      0    71         0      0
2           1       3    0   26      0      0     7         2      1
3           1       1    0   35      1      0    53         2      0
4           0       3    1   35      0      0     8         2      1
..        ...     ...  ...  ...    ...    ...   ...       ...    ...
886         0       2    1   27      0      0    13         2      1
887         1       1    0   19      0      0    30         2      1
888         0       3    0   29      1      2    23         2      0
889         1       1    1   26      0      0    30         0      1
890         0       3    1   32      0      0     7         1      1

[889 rows x 9 columns]

## KNN 

In [79]:
# do feature scaling for age, fare, passenger class (pclass)
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_Train_scaled = scaler.fit_transform(X_Train)
# X_Train_scaled
X_Test_scaled = scaler.fit_transform(X_Test)

In [80]:
from sklearn.neighbors import KNeighborsClassifier

model_knn = KNeighborsClassifier(n_neighbors=5)
# n_neighbors=k

model_knn.fit(X=X_Train_scaled,y=y_train)


KNeighborsClassifier()

In [81]:
y_pred_knn = model_knn.predict(X_Test)
y_pred_knn_scaled = model_knn.predict(X_Test_scaled)
# print(y_pred_knn_scaled)
# print("__________________________ACTUAL BELOW__________________________")
# print(Y)

In [82]:
# find accuracy/confusion matrix
# scaled
cm_knn = confusion_matrix(y_true=y_test,y_pred=y_pred_knn_scaled)
cm_knn


array([[91, 15],
       [19, 53]])

In [83]:
# find accuracy/confusion matrix
# non scaled
cm_knn_ns = confusion_matrix(y_true=y_test,y_pred=y_pred_knn)
cm_knn_ns


array([[63, 43],
       [21, 51]])

In [84]:
c_report_knn = classification_report(y_true=y_test,y_pred=y_pred_knn)
print(c_report_knn)

# 0.775
accuraccy_knn = accuracy_score(y_true=y_test, y_pred=y_pred_knn)
print("Accuraccy non scaled: ", accuraccy_knn)
print("Accuraccy scaled: ", accuracy_score(y_true=y_test,y_pred=y_pred_knn_scaled))

              precision    recall  f1-score   support

           0       0.75      0.59      0.66       106
           1       0.54      0.71      0.61        72

    accuracy                           0.64       178
   macro avg       0.65      0.65      0.64       178
weighted avg       0.67      0.64      0.64       178

Accuraccy non scaled:  0.6404494382022472
Accuraccy scaled:  0.8089887640449438


## Navie Bayes

In [86]:
X_Train

pclass  sex  age  sibsp  parch  fare  embarked  alone
759       1    0   33      0      0    86         2      1
475       1    1   29      0      0    52         2      1
265       2    1   36      0      0    10         2      1
50        3    1    7      4      1    39         2      0
872       1    1   33      0      0     5         2      1
..      ...  ...  ...    ...    ...   ...       ...    ...
491       3    1   21      0      0     7         2      1
97        1    1   23      0      1    63         0      0
263       1    1   40      0      0     0         2      1
239       2    1   33      0      0    12         2      1
44        3    0   19      0      0     7         1      1

[711 rows x 8 columns]

In [87]:
from sklearn.naive_bayes import GaussianNB

naive_bayes_model = GaussianNB()
naive_bayes_model.fit(X_Train,y_train)

GaussianNB()

In [88]:
naive_bayes_predict = naive_bayes_model.predict(X=X_Test)
naive_bayes_predict

array([0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1])

In [89]:
confusion_matrix(y_true=y_test,y_pred=naive_bayes_predict)

array([[89, 17],
       [20, 52]])

In [90]:
print("Accuraccy non scaled: ", accuracy_score(y_true=y_test,y_pred=naive_bayes_predict))

Accuraccy non scaled:  0.7921348314606742


In [91]:
print(classification_report(y_true=y_test,y_pred=naive_bayes_predict))

              precision    recall  f1-score   support

           0       0.82      0.84      0.83       106
           1       0.75      0.72      0.74        72

    accuracy                           0.79       178
   macro avg       0.79      0.78      0.78       178
weighted avg       0.79      0.79      0.79       178



In [92]:
# knn with scaled
naive_bayes_model_scaled = GaussianNB()
naive_bayes_model_scaled.fit(X_Train_scaled,y_train)
naive_bayes_predict_scaled = naive_bayes_model_scaled.predict(X=X_Test_scaled)
naive_bayes_predict_scaled
print(confusion_matrix(y_true=y_test,y_pred=naive_bayes_predict_scaled))
print("Accuraccy scaled: ", accuracy_score(y_true=y_test,y_pred=naive_bayes_predict_scaled))
print(classification_report(y_true=y_test,y_pred=naive_bayes_predict_scaled))

[[90 16]
 [27 45]]
Accuraccy scaled:  0.7584269662921348
              precision    recall  f1-score   support

           0       0.77      0.85      0.81       106
           1       0.74      0.62      0.68        72

    accuracy                           0.76       178
   macro avg       0.75      0.74      0.74       178
weighted avg       0.76      0.76      0.75       178



## Decision Tree

In [93]:
from sklearn.tree import DecisionTreeClassifier

model_decision_tree=DecisionTreeClassifier(random_state=42)

model_decision_tree.fit(X=X_Train,y=y_train)
model_decision_tree

DecisionTreeClassifier(random_state=42)

In [94]:
pred_d_tree = model_decision_tree.predict(X_Test)
pred_d_tree

array([0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0])

In [95]:
# confusion matrix
print(confusion_matrix(y_true=y_test,y_pred=pred_d_tree))
print(classification_report(y_true=y_test,y_pred=pred_d_tree))
print("Accuracy score: ",accuracy_score(y_true=y_test,y_pred=pred_d_tree))

[[91 15]
 [17 55]]
              precision    recall  f1-score   support

           0       0.84      0.86      0.85       106
           1       0.79      0.76      0.77        72

    accuracy                           0.82       178
   macro avg       0.81      0.81      0.81       178
weighted avg       0.82      0.82      0.82       178

Accuracy score:  0.8202247191011236


In [96]:
# decision tree with scaled features

model_decision_tree_scaled=DecisionTreeClassifier(random_state=42)

model_decision_tree_scaled.fit(X=X_Train_scaled,y=y_train)
model_decision_tree_scaled

pred_d_tree_scaled = model_decision_tree_scaled.predict(X_Test_scaled)
pred_d_tree_scaled

# confusion matrix
print(confusion_matrix(y_true=y_test,y_pred=pred_d_tree_scaled))
print(classification_report(y_true=y_test,y_pred=pred_d_tree_scaled))
print("Accuracy score: ",accuracy_score(y_true=y_test,y_pred=pred_d_tree_scaled))

[[92 14]
 [20 52]]
              precision    recall  f1-score   support

           0       0.82      0.87      0.84       106
           1       0.79      0.72      0.75        72

    accuracy                           0.81       178
   macro avg       0.80      0.80      0.80       178
weighted avg       0.81      0.81      0.81       178

Accuracy score:  0.8089887640449438


## SVM - Support Vector Machine

In [97]:
from sklearn.svm import SVC
# support vector classifier

model_svm = SVC(kernel="rbf")

model_svm.fit(X=X_Train_scaled,y=y_train)
model_svm

SVC()

In [100]:
pred_svm = model_svm.predict(X_Test_scaled)

In [101]:
pred_svm

array([0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0])

In [102]:
print("SVM Accuracy: ", accuracy_score(y_true=y_test,y_pred=pred_svm))

SVM Accuracy:  0.8651685393258427


In [103]:
print(confusion_matrix(y_true=y_test,y_pred=pred_svm))
print(classification_report(y_true=y_test,y_pred=pred_svm))
# print("Accuracy score: ",accuracy_score(y_true=y_test,y_pred=pred_svm))

[[101   5]
 [ 19  53]]
              precision    recall  f1-score   support

           0       0.84      0.95      0.89       106
           1       0.91      0.74      0.82        72

    accuracy                           0.87       178
   macro avg       0.88      0.84      0.85       178
weighted avg       0.87      0.87      0.86       178



In [104]:
# trying out it with non scaled features

model_svm_nonscaled = SVC(kernel="rbf")

model_svm_nonscaled.fit(X=X_Train,y=y_train)
model_svm_nonscaled

pred_svm_nonscaled = model_svm_nonscaled.predict(X_Test)

print(confusion_matrix(y_true=y_test,y_pred=pred_svm_nonscaled))
print(classification_report(y_true=y_test,y_pred=pred_svm_nonscaled))
print("Accuracy score: ",accuracy_score(y_true=y_test,y_pred=pred_svm_nonscaled))

[[94 12]
 [52 20]]
              precision    recall  f1-score   support

           0       0.64      0.89      0.75       106
           1       0.62      0.28      0.38        72

    accuracy                           0.64       178
   macro avg       0.63      0.58      0.57       178
weighted avg       0.64      0.64      0.60       178

Accuracy score:  0.6404494382022472
